#!/usr/bin/bash

# Removes old revisions of snaps

# DISCLAIMER : CLOSE ALL SNAPS BEFORE RUNNING THIS

echo "Please enter your password to start the service"
sudo -v

set -eu

# Get initial disk usage in 1K blocks
initial_usage=$(df --block-size=1K --output=used / | tail -n 1)

snap list --all | awk '/disabled/{print $1, $3}' |
  while read snapname revision; do
    sudo snap remove "$snapname" --revision="$revision"
  done

# Get final disk usage in 1K blocks
final_usage=$(df --block-size=1K --output=used / | tail -n 1)

# Calculate the difference in 1K blocks
freed_space_kb=$((initial_usage - final_usage))

# Convert to megabytes
freed_space_mb=$((freed_space_kb / 1024))

echo "Total data freed: ${freed_space_mb}MB"