#!/usr/bin/bash

# Idea -> Could be either copying the entire folder into repo or extracting all the data to the folder 

declare -A SRC=(
    ["piscine"]="/mnt/nfs/homes/pjaguin/Desktop/Piscine/Piscine"
)
declare -A DEST=(
    ["piscine"]="/mnt/nfs/homes/pjaguin/Desktop/Perso/42"
)

usage() {
    echo "Copy paste a project from 42 repo to your private repository without the .git"
    echo "Usage: $0 [project_name]"
    echo "Available projects:"
    for project in ${!DEST[@]}; do
        echo "  - $project"
    done
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi


project_name=$1
echo $project_name

copy_project() {
	local project_path=${SRC[$project_name]}
	local repo_path=${DEST[$project_name]}

	if [ -z "$project_path" ]; then
        echo "Unknown project: $project_name"
        exit 1
    fi

	cd "$project_path" || exit

	rsync -av --exclude=".*" "$project_path" "$repo_path" #exclude hidden files

	cd "$repo_path" || exit

	git add . && git commit -m "`date +'%Y-%m-%d %H:%M:%S'` autosave $project_name " && git push
}

copy_project
