#!/usr/bin/bash

# REQUIRE IMAGEMAGICK INSTALLED
# sudo apt-get install imagemagick

if ! command -v convert &> /dev/null; then
  echo "ImageMagick is not installed. Please install it first."
  exit 1
fi

# Default quality and delete option
quality=85
delete_files=false

# Parse options
while getopts "q:d" opt; do
  case $opt in
    q)
      quality=$OPTARG
      ;;
    d)
      delete_files=true
      ;;
    *)
      echo "Usage: $0 [-q quality] [-d]"
      exit 1
      ;;
  esac
done

shift $((OPTIND -1))

convert_to_webp() {
  local input_file=$1
  local quality=$2
  local output_file="${input_file%.*}.webp"
  if convert -quality "$quality" "$input_file" "$output_file"; then
    echo "Converted $input_file to $output_file"
  else
    echo "Failed to convert $input_file"
  fi
}

export -f convert_to_webp

# Find and convert all PNG, JPG, and JPEG files in the current directory and its subdirectories
find . -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" \) -exec bash -c 'convert_to_webp "$0" '"$quality" {} \;

# Optionally, remove the original files
if [ "$delete_files" = true ]; then
  echo "Deleting all the original files..."
  find . -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" \) -exec rm -f {} \;
fi