#!/usr/bin/bash

# REQUIRE IMAGEMAGICK INSTALLED
# sudo apt-get install imagemagick

if ! command -v convert &> /dev/null; then
  echo "ImageMagick is not installed. Please install it first."
  exit 1
fi

if [ $# -eq 0 ]; then
  echo "Usage: $0 <quality>"
  exit 1
fi

quality=$1

convert_to_webp() {
  local input_file=$1
  local quality=$2
  local output_file="${input_file%.*}.webp"
  if convert -quality "$quality" "$input_file" "$output_file"; then
    echo "Converted $input_file to $output_file"
  else
    echo "Failed to convert $input_file"
  fi
}

export -f convert_to_webp

# Find and convert all PNG, JPG, and JPEG files in the current directory and its subdirectories
find . -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" \) -exec bash -c 'convert_to_webp "$0" '"$quality" {} \;

# Optionally, remove the original files
# rm -rf ./*.png ./*.jpg ./*.jpeg