#!/usr/bin/bash

# REQUIRE IMAGEMAGICK INSTALLED
# sudo apt-get install imagemagick

convert_to_webp() {
  local input_file=$1
  local output_file="${input_file%.*}.webp"
  if convert -quality 85 "$input_file" "$output_file"; then
    echo "Converted $input_file to $output_file"
  else
    echo "Failed to convert $input_file"
  fi
}

export -f convert_to_webp

# Find and convert all PNG, JPG, and JPEG files in the current directory and its subdirectories
find . -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" \) -exec bash -c 'convert_to_webp "$0"' {} \;